# Generated by Django 5.0.2 on 2024-04-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('group_id', models.IntegerField()),
                ('fire_id', models.CharField(max_length=255)),
                ('is_problem', models.BooleanField()),
                ('progress_status', models.IntegerField()),
            ],
        ),
    ]
